### ISSUE TITLE
furnaces don't open 

### ISSUE THREAD

**Issue by Crystalcherryrose** [jiink/smelting-in-a-pinch#1]
every time i try to open it, it just closes right away

**Comment by jiink** [comment]
Thank you for taking the time to open an issue. Closing your issue immediately with no comment makes me suspect it was a mistake.

If this is still a problem, I need more details in order to be able to replicate it myself and solve it:
- What version of Minecraft are you on?
- What version of the mod?
- Were you on singleplayer, or multiplayer?
- What other mods do you have installed?

If you closed the issue intentionally, then no worries.
